package ca.bcit.comp1510.ch04;

import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.text.Text;
import javafx.scene.layout.FlowPane;
import javafx.stage.Stage;

/**
 * A variation on the PushCounter program that uses a full EventHandler class.
 * 
 * @author Lewis & Loftus 9e
 * @author BCIT
 * @version 2017
 */
public class PushCounter2 extends Application {
    /** Holds the number of time the button is pressed. */
    private int count;

    /** Displays the number of times the button is pressed. */
    private Text countText;

    /**
     * Presents a GUI containing a button and text that displays how many times
     * the button is pushed.
     * 
     * @param primaryStage a Stage
     */
    public void start(Stage primaryStage) {
        count = 0;
        countText = new Text("Pushes: 0");

        Button push = new Button("Push Me!");
        
        //Old way, pass object that contains action method
        push.setOnAction(new ButtonHandler());

        FlowPane pane = new FlowPane(push, countText);
        pane.setAlignment(Pos.CENTER);

        final int horizontalGap = 20;
        pane.setHgap(horizontalGap);
        pane.setStyle("-fx-background-color: cyan");
        
        final int appWidth = 300;
        final int appHeight = 100;
        Scene scene = new Scene(pane, appWidth, appHeight);

        primaryStage.setTitle("Push Counter 2");
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    /**
     * Launches the JavaFX application.
     * 
     * @param args command-line arguments
     */
    public static void main(String[] args) {
        launch(args);
    }

    /**
     * ButtonHandler is a class that handles the ActionEvent generated by the
     * Button in PushCounter.
     * 
     * @author Lewis & Loftus 9e
     * @author BCIT
     * @version 2017
     */
    private class ButtonHandler implements EventHandler<ActionEvent> {

        /**
         * Handles the event.
         * 
         * @param event signals button was pressed
         */
        public void handle(ActionEvent event) {
            count++;
            countText.setText("Pushes: " + count);
        }
    }
}

